var webUrl = "https://BeatCovid.xyz";
export default function format(data) {
  const {
    Name,
    Phone,
    Patient_Name,
    Patient_Age,
    Patient_Location,
    Requirement
  } = data;

  var keys = Object.keys(Requirement);
  var requirementInfo = keys.filter(function (key) {
    return Requirement[key];
  });

  return `
    Name: ${Name}
    Phone: ${Phone}
    Patient's Name: ${Patient_Name}
    Patient's Age : ${Patient_Age}
    Patient's Location : ${Patient_Location}
    Requirement: ${requirementInfo}
    Generated by ${webUrl}
  `;
}
